### ISSUE TITLE
Other OPC-official Nodesets do not work with this tool

### ISSUE THREAD

**Issue by jwise-cesmii** [barnstee/UANodesetWebViewer#1]
The following OPC UA Nodesets do not work with the tool:

- https://github.com/OPCFoundation/UA-Nodeset/blob/v1.04/MachineTool/Opc.Ua.MachineTool.NodeSet2.xml
- https://github.com/OPCFoundation/UA-Nodeset/blob/v1.04/Scales/Opc.Ua.Scales.NodeSet2.xml
- https://github.com/OPCFoundation/UA-Nodeset/blob/v1.04/Robotics/Opc.Ua.Robotics.NodeSet2.xml

When used in place of the Opc.Ua.Station.Config.xml, the method `ImportNodeset2Xml` silently fails and the AssetAdminShell folder is not created in the server's namespace. Tracing the error shows it happening at `AddPredefinedNode` in `StationNodeManager.cs`:
`Error adding node to nodeset: A valid supertype identifier is required.`

**Comment by barnstee** [comment]
Moved to this repo as the OPCUA2AAS is not meant to load external nodeset files, while this tool is.

**Comment by barnstee** [comment]
Fixed with checkin https://github.com/barnstee/UANodesetWebViewer/commit/932f525b1a56fa33697950d9245b32e343b3be64
