### ISSUE TITLE
Anti-forgery exception

### ISSUE THREAD

**Issue by murdockcrc** [barnstee/UANodesetWebViewer#5]
When uploading an XML file and submitting the file to get it parsed, the console throws the following error:

```
 Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery[7]
      An exception was thrown while deserializing the token.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
 ---> System.Security.Cryptography.CryptographicException: The key {guid} was not found in the key ring.
```

Wondering if you can repro this issue too?

**Comment by barnstee** [comment]
See here: https://stackoverflow.com/questions/42103004/using-antiforgery-in-asp-net-core-and-got-error-the-antiforgery-token-could-no
TL;DR" clear your cookies if you ever used that domain/port from other machines.

**Comment by barnstee** [comment]
Did it resolve the issue?

**Comment by barnstee** [comment]
Closing due to inavctivity.
