### ISSUE TITLE
Error "Object reference not set to an instance of an object." wihle loading namespace zero

### ISSUE THREAD

**Issue by StenGruener** [barnstee/UANodesetWebViewer#6]
Hello,

Running the tool from docker hub `docker run -p 8080:80 barnstee/uanodesetwebviewer:latest`, I am trying to load the namespace zero (https://github.com/OPCFoundation/UA-Nodeset/blob/v1.04/Schema/Opc.Ua.NodeSet2.xml) into it. I need to load it, since my model depends on ns0.

Unfortunately, I get the error "Object reference not set to an instance of an object.". 

Is there any trick, should I try an older version of NS0?

BR
-Sten

p.s.: same error when using "ghcr.io/barnstee/uanodesetwebviewer:main" as image, which one is the current one?

**Comment by barnstee** [comment]
This is a bug, working on a fix.

**Comment by barnstee** [comment]
Fixed with checkin https://github.com/barnstee/UANodesetWebViewer/commit/fb31e2aff9837e6be3088fbe6f48a9f7dbe16e5a

**Comment by StenGruener** [comment]
👍
